[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm install ajv@^8.0.0 --legacy-peer-deps && CI=false npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/package.json"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
